"""set null on task_completions user_who_completed_id fk

Revision ID: 11b0cf014657
Revises: 7ec4f67379f9
Create Date: 2026-03-27 13:56:11.184333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '11b0cf014657'
down_revision: Union[str, Sequence[str], None] = '7ec4f67379f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('house_users_house_id_fkey'), 'house_users', type_='foreignkey')
    op.create_foreign_key(None, 'house_users', 'houses', ['house_id'], ['id'])
    op.drop_constraint(op.f('role_house_users_house_id_fkey'), 'role_house_users', type_='foreignkey')
    op.create_foreign_key(None, 'role_house_users', 'houses', ['house_id'], ['id'])
    op.drop_constraint(op.f('task_completions_task_life_id_fkey'), 'task_completions', type_='foreignkey')
    op.drop_constraint(op.f('task_completions_user_who_completed_id_fkey'), 'task_completions', type_='foreignkey')
    op.create_foreign_key(None, 'task_completions', 'users', ['user_who_completed_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'task_completions', 'task_lives', ['task_life_id'], ['id'])
    op.drop_constraint(op.f('task_lives_task_id_fkey'), 'task_lives', type_='foreignkey')
    op.create_foreign_key(None, 'task_lives', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(op.f('tasks_house_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'houses', ['house_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_house_id_fkey'), 'tasks', 'houses', ['house_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'task_lives', type_='foreignkey')
    op.create_foreign_key(op.f('task_lives_task_id_fkey'), 'task_lives', 'tasks', ['task_id'], ['id'],
                          ondelete='CASCADE')
    op.drop_constraint(None, 'task_completions', type_='foreignkey')
    op.drop_constraint(None, 'task_completions', type_='foreignkey')
    op.create_foreign_key(op.f('task_completions_user_who_completed_id_fkey'), 'task_completions', 'users',
                          ['user_who_completed_id'], ['id'])
    op.create_foreign_key(op.f('task_completions_task_life_id_fkey'), 'task_completions', 'task_lives',
                          ['task_life_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'role_house_users', type_='foreignkey')
    op.create_foreign_key(op.f('role_house_users_house_id_fkey'), 'role_house_users', 'houses', ['house_id'], ['id'],
                          ondelete='CASCADE')
    op.drop_constraint(None, 'house_users', type_='foreignkey')
    op.create_foreign_key(op.f('house_users_house_id_fkey'), 'house_users', 'houses', ['house_id'], ['id'],
                          ondelete='CASCADE')
    # ### end Alembic commands ###
