"""add_created_at_time_on_the_task

Revision ID: 133920bf2a24
Revises: 1ea977b4a77c
Create Date: 2026-04-08 14:18:06.038783

"""
from typing import Sequence, Union

from datetime import datetime

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '133920bf2a24'
down_revision: Union[str, Sequence[str], None] = '1ea977b4a77c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('date_created', sa.DateTime(), nullable=True))

    connection = op.get_bind()

    # For each task, find the earliest completion date across all its task_lives
    result = connection.execute(sa.text("""
                                        SELECT t.id, MIN(tc.completed_at) as first_completed_at
                                        FROM tasks t
                                                 LEFT JOIN task_lives tl ON tl.task_id = t.id
                                                 LEFT JOIN task_completions tc ON tc.task_life_id = tl.id
                                        GROUP BY t.id
                                        """))

    now = datetime.now()
    for row in result:
        date_created = row.first_completed_at if row.first_completed_at else now
        connection.execute(
            sa.text("UPDATE tasks SET date_created = :date_created WHERE id = :task_id"),
            {"date_created": date_created, "task_id": row.id}
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'date_created')
    # ### end Alembic commands ###
