"""add_time_to_complete_task

Revision ID: 1ea977b4a77c
Revises: 6bfab9562ee0
Create Date: 2026-04-08 11:09:59.218364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1ea977b4a77c'
down_revision: Union[str, Sequence[str], None] = '6bfab9562ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('time_to_complete', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'time_to_complete')
    # ### end Alembic commands ###
