"""Add relationship between users and houses fix

Revision ID: 329e01db1f83
Revises: f63ef1eaf881
Create Date: 2026-02-23 09:46:19.677433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '329e01db1f83'
down_revision: Union[str, Sequence[str], None] = 'f63ef1eaf881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('house_users', sa.Column('house_id', sa.Integer(), nullable=False))
    op.add_column('house_users', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'house_users', 'houses', ['house_id'], ['id'])
    op.create_foreign_key(None, 'house_users', 'users', ['user_id'], ['id'])
    op.drop_column('house_users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('house_users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'house_users', type_='foreignkey')
    op.drop_constraint(None, 'house_users', type_='foreignkey')
    op.drop_column('house_users', 'user_id')
    op.drop_column('house_users', 'house_id')
    # ### end Alembic commands ###
