"""cascade delete on role_house_users user_id fk

Revision ID: 5649bc8e6ad1
Revises: 11b0cf014657
Create Date: 2026-03-27 14:12:18.967904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5649bc8e6ad1'
down_revision: Union[str, Sequence[str], None] = '11b0cf014657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('role_house_users_user_id_fkey'), 'role_house_users', type_='foreignkey')
    op.create_foreign_key(None, 'role_house_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_house_users', type_='foreignkey')
    op.create_foreign_key(op.f('role_house_users_user_id_fkey'), 'role_house_users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
