"""Add taskCategories table + relationship

Revision ID: 635e5e4177d3
Revises: 329e01db1f83
Create Date: 2026-02-23 09:52:59.724250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '635e5e4177d3'
down_revision: Union[str, Sequence[str], None] = '329e01db1f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_categories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_task_categories_id'), 'task_categories', ['id'], unique=False)
    op.create_index(op.f('ix_task_categories_name'), 'task_categories', ['name'], unique=False)

    # Drop the wrongly created table if it exists
    op.execute("DROP TABLE IF EXISTS taskCategories")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_categories_name'), table_name='task_categories')
    op.drop_index(op.f('ix_task_categories_id'), table_name='task_categories')
    op.drop_table('task_categories')
    # ### end Alembic commands ###
