"""add_user_configuration_json_to_user

Revision ID: 6bfab9562ee0
Revises: 9d0d628422b5
Create Date: 2026-04-02 10:56:43.387050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '6bfab9562ee0'
down_revision: Union[str, Sequence[str], None] = '9d0d628422b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_configuration', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_configuration')
    # ### end Alembic commands ###
