"""cascade delete on house_users and task_life_users user_id fk

Revision ID: 87ba6626a365
Revises: 5649bc8e6ad1
Create Date: 2026-03-27 14:13:29.615738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '87ba6626a365'
down_revision: Union[str, Sequence[str], None] = '5649bc8e6ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('house_users_user_id_fkey'), 'house_users', type_='foreignkey')
    op.create_foreign_key(None, 'house_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('task_life_users_user_id_fkey'), 'task_life_users', type_='foreignkey')
    op.create_foreign_key(None, 'task_life_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_life_users', type_='foreignkey')
    op.create_foreign_key(op.f('task_life_users_user_id_fkey'), 'task_life_users', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'house_users', type_='foreignkey')
    op.create_foreign_key(op.f('house_users_user_id_fkey'), 'house_users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
