"""cascade delete on houses fk chain

Revision ID: 9d0d628422b5
Revises: 87ba6626a365
Create Date: 2026-03-27 14:26:59.224355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9d0d628422b5'
down_revision: Union[str, Sequence[str], None] = '87ba6626a365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('house_users_house_id_fkey'), 'house_users', type_='foreignkey')
    op.create_foreign_key(None, 'house_users', 'houses', ['house_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('role_house_users_house_id_fkey'), 'role_house_users', type_='foreignkey')
    op.create_foreign_key(None, 'role_house_users', 'houses', ['house_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('task_completions_task_life_id_fkey'), 'task_completions', type_='foreignkey')
    op.create_foreign_key(None, 'task_completions', 'task_lives', ['task_life_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('task_life_users_task_life_id_fkey'), 'task_life_users', type_='foreignkey')
    op.create_foreign_key(None, 'task_life_users', 'task_lives', ['task_life_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('task_lives_task_id_fkey'), 'task_lives', type_='foreignkey')
    op.create_foreign_key(None, 'task_lives', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tasks_house_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'houses', ['house_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_house_id_fkey'), 'tasks', 'houses', ['house_id'], ['id'])
    op.drop_constraint(None, 'task_lives', type_='foreignkey')
    op.create_foreign_key(op.f('task_lives_task_id_fkey'), 'task_lives', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'task_life_users', type_='foreignkey')
    op.create_foreign_key(op.f('task_life_users_task_life_id_fkey'), 'task_life_users', 'task_lives', ['task_life_id'],
                          ['id'])
    op.drop_constraint(None, 'task_completions', type_='foreignkey')
    op.create_foreign_key(op.f('task_completions_task_life_id_fkey'), 'task_completions', 'task_lives',
                          ['task_life_id'], ['id'])
    op.drop_constraint(None, 'role_house_users', type_='foreignkey')
    op.create_foreign_key(op.f('role_house_users_house_id_fkey'), 'role_house_users', 'houses', ['house_id'], ['id'])
    op.drop_constraint(None, 'house_users', type_='foreignkey')
    op.create_foreign_key(op.f('house_users_house_id_fkey'), 'house_users', 'houses', ['house_id'], ['id'])
    # ### end Alembic commands ###
