"""add Tasks Tables

Revision ID: ae576a5ad968
Revises: 7c9f558f849d
Create Date: 2026-03-05 10:00:17.070679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae576a5ad968'
down_revision: Union[str, Sequence[str], None] = '7c9f558f849d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_recurrences',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('frequency_days', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('task_lives',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('task_id', sa.Integer(), nullable=True),
                    sa.Column('recurrence_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['recurrence_id'], ['task_recurrences.id'], ),
                    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('task_completions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('task_life_id', sa.Integer(), nullable=True),
                    sa.Column('user_who_completed_id', sa.Integer(), nullable=True),
                    sa.Column('completed_at', sa.DateTime(), nullable=True),
                    sa.Column('period_key', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['task_life_id'], ['task_lives.id'], ),
                    sa.ForeignKeyConstraint(['user_who_completed_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('task_life_users',
                    sa.Column('task_life_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['task_life_id'], ['task_lives.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('task_life_id', 'user_id')
                    )
    op.drop_index(op.f('ix_assignments_id'), table_name='assignments')
    op.drop_table('assignments')
    op.execute("ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_category_id_fkey")
    op.execute("ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_category_id_fkey1")
    op.drop_index(op.f('ix_task_categories_id'), table_name='task_categories')
    op.drop_index(op.f('ix_task_categories_name'), table_name='task_categories')
    op.drop_table('task_categories')
    op.add_column('tasks', sa.Column('weight', sa.Integer(), nullable=True))
    op.drop_column('tasks', 'is_completed')
    op.drop_column('tasks', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tasks_category_id_fkey'), 'tasks', 'task_categories', ['category_id'], ['id'])
    op.drop_column('tasks', 'weight')
    op.create_table('task_categories',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('task_categories_pkey'))
                    )
    op.create_index(op.f('ix_task_categories_name'), 'task_categories', ['name'], unique=False)
    op.create_index(op.f('ix_task_categories_id'), 'task_categories', ['id'], unique=False)
    op.create_table('assignments',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('assignments_task_id_fkey')),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('assignments_user_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f('assignments_pkey'))
                    )
    op.create_index(op.f('ix_assignments_id'), 'assignments', ['id'], unique=False)
    op.drop_table('task_life_users')
    op.drop_table('task_completions')
    op.drop_table('task_lives')
    op.drop_table('task_recurrences')
    # ### end Alembic commands ###
