"""add unique constraint to role_house_users

Revision ID: cefc3fd67439
Revises: e13ff1300265
Create Date: 2026-03-17 16:03:02.494635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'cefc3fd67439'
down_revision: Union[str, Sequence[str], None] = 'e13ff1300265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_role_house_user', 'role_house_users', ['user_id', 'house_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_role_house_user', 'role_house_users', type_='unique')
    # ### end Alembic commands ###
